# List 5: Metropolis algorithm

We have two urns with balls. There are 4 black and 3 white balls.

We have four different possible states:
  1. WWW | BBBB
  2. WWB | BBBW
  3. WBB | BBWW
  4. BBB | BWWW

In [1]:
import numpy as np

The initial state vector corresponding to the WWW | BBBB state.

In [2]:
P_init = np.array([1,0,0,0])

The transition matrix.

In [39]:
W = np.array([[0, 12, 0, 0], [1, 5, 6, 0], [0, 4, 6, 2], [0, 0, 9, 3]])/12
print(W)

[[ 0.          1.          0.          0.        ]
 [ 0.08333333  0.41666667  0.5         0.        ]
 [ 0.          0.33333333  0.5         0.16666667]
 [ 0.          0.          0.75        0.25      ]]


Example of the the third step in evolution $P^{(2)}=P^{(0)}W^2$.

In [28]:
np.dot(np.dot(P_init, W),W)

array([ 0.08333333,  0.41666667,  0.5       ,  0.        ])

Below there are examples of the evolution of the transition matrix W - its powers.

In [29]:
np.linalg.matrix_power(W, 4)

array([[ 0.03530093,  0.36400463,  0.50347222,  0.09722222],
       [ 0.03033372,  0.3547936 ,  0.50665509,  0.10821759],
       [ 0.02797068,  0.33777006,  0.51765046,  0.1166088 ],
       [ 0.02430556,  0.32465278,  0.52473958,  0.12630208]])

In [30]:
np.linalg.matrix_power(W, 8)

array([[ 0.02873327,  0.34361752,  0.51383681,  0.1138124 ],
       [ 0.02863479,  0.34318617,  0.51408646,  0.11409257],
       [ 0.02854649,  0.34272431,  0.51436663,  0.11436257],
       [ 0.0284531 ,  0.3422777 ,  0.51463155,  0.11463765]])

In [31]:
np.linalg.matrix_power(W, 16)

array([[ 0.02857157,  0.34285785,  0.51428529,  0.11428529],
       [ 0.02857149,  0.34285744,  0.51428554,  0.11428554],
       [ 0.02857141,  0.34285702,  0.51428579,  0.11428579],
       [ 0.02857132,  0.34285661,  0.51428603,  0.11428603]])

In [32]:
np.linalg.matrix_power(W, 32)

array([[ 0.02857143,  0.34285714,  0.51428571,  0.11428571],
       [ 0.02857143,  0.34285714,  0.51428571,  0.11428571],
       [ 0.02857143,  0.34285714,  0.51428571,  0.11428571],
       [ 0.02857143,  0.34285714,  0.51428571,  0.11428571]])

The evolution of the initial state WWW | BBBB over 30 steps.

We can see that after 20 steps the system reaches the stationary distribution.

In [33]:
for i in range(50):
  P = np.dot(P_init, np.linalg.matrix_power(W, i))
  print(f'P({i}): {P}')

P(0): [ 1.  0.  0.  0.]
P(1): [ 0.  1.  0.  0.]
P(2): [ 0.08333333  0.41666667  0.5         0.        ]
P(3): [ 0.03472222  0.42361111  0.45833333  0.08333333]
P(4): [ 0.03530093  0.36400463  0.50347222  0.09722222]
P(5): [ 0.03033372  0.3547936   0.50665509  0.10821759]
P(6): [ 0.02956613  0.34704941  0.51188754  0.11149691]
P(7): [ 0.02892078  0.34479924  0.51309116  0.11318882]
P(8): [ 0.02873327  0.34361752  0.51383681  0.1138124 ]
P(9): [ 0.02863479  0.34318617  0.51408646  0.11409257]
P(10): [ 0.02859885  0.34299119  0.51420575  0.11420422]
P(11): [ 0.0285826   0.34291376  0.51425163  0.11425201]
P(12): [ 0.02857615  0.34288054  0.5142717   0.11427161]
P(13): [ 0.02857338  0.34286694  0.51427983  0.11427985]
P(14): [ 0.02857225  0.34286121  0.51428327  0.11428327]
P(15): [ 0.02857177  0.34285884  0.51428469  0.1142847 ]
P(16): [ 0.02857157  0.34285785  0.51428529  0.11428529]
P(17): [ 0.02857149  0.34285744  0.51428554  0.11428554]
P(18): [ 0.02857145  0.34285727  0.51428564  0.1

In [38]:
from scipy.linalg import eig
eigs, vecs = eig(W.T)

In [25]:
vecs[:,0]/vecs[:,0].sum() - P

array([ -4.85722573e-17,  -3.88578059e-16,   0.00000000e+00,
        -2.77555756e-17])

In [26]:
P

array([ 0.02857143,  0.34285714,  0.51428571,  0.11428571])

In [37]:
vecs

array([[  5.00000000e-01,  -7.52946966e-01,   9.31380631e-01,
          8.84651737e-01],
       [  5.00000000e-01,  -3.13727903e-01,  -2.32845158e-01,
          4.52147228e-17],
       [  5.00000000e-01,   1.25491161e-01,   1.55230105e-01,
         -1.47441956e-01],
       [  5.00000000e-01,   5.64710225e-01,  -2.32845158e-01,
          4.42325868e-01]])